// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMRtDV1UgTzunY6pvJCw5nuyNWFlr340',
    appId: '1:404715032763:web:153cf725528d429a30d99e',
    messagingSenderId: '404715032763',
    projectId: 'fir-8f0f9',
    authDomain: 'fir-8f0f9.firebaseapp.com',
    storageBucket: 'fir-8f0f9.appspot.com',
    measurementId: 'G-PSLQ7WZVSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAih_WE3vML5aBBnJ3jqRQ9kz6cjTJxJCU',
    appId: '1:404715032763:android:7f4a352b171899c630d99e',
    messagingSenderId: '404715032763',
    projectId: 'fir-8f0f9',
    storageBucket: 'fir-8f0f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ll_nyb2qEvMPM1P3bjfVdEcxPApyWmY',
    appId: '1:404715032763:ios:6c6ef49afe54267b30d99e',
    messagingSenderId: '404715032763',
    projectId: 'fir-8f0f9',
    storageBucket: 'fir-8f0f9.appspot.com',
    iosBundleId: 'com.example.fullFlutterFirebaseAuth',
  );
}